---
title: "Project Stat 153"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(astsa)
library(forecast)
library(xts)
library(TSA)
library(dplyr)
```


```{r}
pgram = function(x){
  m = floor(length(x)/2)
  pgram = abs(fft(x)[2:(m+1)])^2/length(x)
  plot(pgram[1:30], type = "h")
  abline(h=0)
  return(pgram)
}
```

## 1.Exploratory data analysis
```{r cars}
rm(list = ls())
popdata = read.csv("POPTHM1.csv",header = T)

pop = popdata$POPTHM
date = as.Date(popdata$DATE,format = "%Y/%m/%d")

pop.ts = ts(pop,start = c(1990,3),frequency =  12)
plot.ts(pop.ts,type = "l", xlab = "Monthly", ylab = "USA population data", main = "USA population for years 1990-2021") 

```
increasing trend

```{r smooth, echo=FALSE}
# Step1:  1st difference
dpop = diff(pop.ts)
t = c(1:length(dpop))
plot(t,dpop,type = "l")
```


```{r smooth, echo=FALSE}
# Step 2:  fit the trend
lm1 = lm(dpop~poly(t,4))  
dpop_lm1_fit=lm1$fitted.values

plot(t,as.numeric(dpop),type = 'l')
lines(t,dpop_lm1_fit)
dpop_lm1_res=lm1$residuals
plot(dpop_lm1_res,type = 'l') 

#待做：对于数据过拟合进行惩罚 AIC

```
```{r}
pgram(dpop_lm1_res[1:324])
```
so the period are 324 / 3 = 108 and 324 / 27 = 12

```{r smooth, echo=FALSE}

v1 = cos(2*pi*t/108)
v2 = sin(2*pi*t/108)


lm2 = lm(dpop_lm1_res~v1+v2)
plot(t,as.numeric(dpop_lm1_res),type = 'l')
lines(t,lm2$fitted.values)

dpop_lm2_res= lm2$residuals
plot(t,dpop_lm2_res,type = 'l')

#检测平稳性



```

```{r pressure1, echo=FALSE}
sm.par=c(0.5,1,1,1,1,1,1,1,1,1,1,1,0.5)
mt = filter(dpop_lm2_res, sm.par/12)
sm.res = dpop_lm2_res - mt
plot(sm.res)

plot(dpop_lm2_res,type ='l')
lines(mt,col = 'red')

```
```{r pressure, echo=FALSE}
ddpop = diff(dpop_lm2_res,12)
plot.ts(ddpop,type = "l")

ddpop.ts = ts(ddpop,start = '1991.3',frequency = 12)
acf2(ddpop.ts,100)
library(astsa)
auto.arima(ddpop.ts)
```
```{r pressure3, echo=FALSE}

for(PP in c(0:3))
  for(QQ in c(0:3))
    for (pp in c(1:4))
      for(qq in c(0:7))
        m4 = sarima(ddpop,p=pp,d=0,q=qq,P=PP,D=0,Q=QQ,S=12)
```

```{r pressure, echo=FALSE}
m1 = sarima(ddpop.ts,p=3,d=0,q=7,P=0,D=0,Q=1,S=12) 
m2 = sarima(ddpop.ts,p=3,d=0,q=7,P=0,D=0,Q=2,S=12)
m3 = sarima(ddpop.ts,p=3,d=0,q=7,P=0,D=0,Q=3,S=12)
#m2 fits best if we look at the LjungBox test and p-value#
```
```{r pressure, echo=FALSE}
m1$AIC
m2$AIC
m3$AIC

m1$AICc
m2$AICc
m3$AICc

m1$BIC
m2$BIC
m3$BIC
```
```{r acf, echo=FALSE}
#question 6
#cal acf pacf
th = c(m2$fit$coef[1:3])
phi = c(m2$fit$coef[4:10],rep(0, 4), m2$fit$coef[11],rep(0, 11),m2$fit$coef[12])
T = 60
corrs = ARMAacf(ar = th,ma = phi, lag.max = T)
par.corrs = ARMAacf(ar = th,ma = phi, lag.max = T, pacf = T)
all.plot = function(x,corr,pcorr){
  acf(x,lag.max = T)
  points(corr[1:60],col='red',type='h')
  pacf(x,lag.max = T)
  points(pcorr[1:60],col='red',type='h')
}
all.plot(as.vector(ddpop.ts),corrs,par.corrs)


#Forecast
modelf1 = sarima.for(ddpop.ts,n.ahead = 12,p=3,d=0,q=7,P=0,D=0,Q=2,S=12)

```
# Model 2

population growth
```{r cars}
dpop = diff(pop.ts)
plot.ts(dpop)
```


First remove the decreasing trend with linear parametric
```{r}
t = 1:length(dpop)
model = lm(dpop ~ poly(t, degree = 2))
plot(t, model$fitted.values, type = "l", col = "blue")
lines(t, dpop)
plot(t, model$residuals, type = "l")
resid = model$residuals
```

```{r}
pgram(resid[1:324])
```

total number / index = period
so 324 / 27 = 12 --> period
and 324 / 3 = 108


```{r}
t = 1:length(dpop)
df = data.frame(t = t, t2 = t^2, v1 = cos(2*pi*t/108), v2 = sin(2*pi*t/108), v3 = cos(2*pi*t/12), v4 =  sin(2*pi*t/12))
m2 = lm(dpop ~ t+t2+v1+v2+v3+v4, df)

plot(t, dpop, type = "l", col = "black")
lines(t, m2$fitted.values, col = "blue")
plot(t, m2$residuals, type = "l")
resid = m2$residuals
```

```{r}
acf2(resid)
```
fit linear trend (up and down - and there might be a bump when it switches) - this makes the mean more constant overtime.

```{r}
d1 = diff(resid)
plot.ts(d1)
```

```{r}
acf2(d1)
```

```{r}
m2a = sarima(resid,p=10,d=1,q=2,P=1,D=0,Q=1,S=12)
```

```{r}
m2b = sarima(resid,p=9,d=1,q=2,P=0,D=0,Q=2,S=12)
```

## Comparing AIC, BIC, AICc
```{r}
m2a$AIC
m2a$BIC
m2a$AICc
```

```{r}
m2b$AIC
m2b$BIC
m2b$AICc
```




```{r}
########################
### Cross Validation ###
########################

# cross validate 2017, 2018, 2019

sse = matrix(NA, nrow=3,ncol=2) # forecasting out 3 different times, with 2 models
for(i in 1:3){
  
  ## Split train/test
  # if using a time series object
  # train = window(l1,start=2004,end=2013+i-.0001)
  # test = window(l1, start=2013+i, end=2013+i+.999)
  # if using a standard vector
  split.point = 309+12*(i-1) # last point of train
  train = as.vector(dpop)[1:split.point]
  test = as.vector(dpop)[(split.point+1):(split.point+12)]
  
  ## Fit model2
  t = 1:length(train)
  df_train = data.frame(t = t, t2 = t^2, v1 = cos(2*pi*t/108), v2 = sin(2*pi*t/108), v3 = cos(2*pi*t/12), v4 =  sin(2*pi*t/12))
  model2 = lm(dpop ~ t+t2+v1+v2+v3+v4, df)
  Xt = model2$residuals
  
  # Predict Model2
  t_pred = (length(train)+1):(length(train)+12)
  new_df = data.frame(t = t_pred, t2 = t_pred^2, v1 = cos(2*pi*t_pred/108), v2 = sin(2*pi*t_pred/108), v3 = cos(2*pi*t_pred/12), v4 =  sin(2*pi*t_pred/12))
  model2_pred = predict(model2, new_df)

  # ## Fit SARIMA
  model2a = sarima.for(Xt,n.ahead = 12,p=10,d=1,q=2,P=1,D=0,Q=1,S=12)
  #lines((train.test.split.point+1):(train.test.split.point+12),test)
  model2b = sarima.for(Xt,n.ahead = 12,p=9,d=1,q=2,P=0,D=0,Q=2,S=12)
  #lines((train.test.split.point+1):(train.test.split.point+12),test)
  # 
  # ## Test
  model2a_pred = model2_pred + model2a$pred
  sse[i,1] = sum((test - model2a_pred)^2)
  plot(c(200:split.point, t_pred), c(train[200:split.point], test), type = "l", col = "black")
  lines(t_pred, model2a_pred, col = "blue")
  
  model2b_pred = model2_pred + model2b$pred
  sse[i,2] = sum((test - model2b_pred)^2)
  plot(c(200:split.point, t_pred), c(train[200:split.point], test), type = "l", col = "black")
  lines(t_pred, model2b_pred, col = "blue")

  
}
```


```{r}
CV_RMSE = sqrt(apply(sse,2,sum))
CV_RMSE
```


